//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MstYangin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adres
    {
        public int Id { get; set; }
        public string KonumX { get; set; }
        public string KonumY { get; set; }
        public string Telefon { get; set; }
        public string Faks { get; set; }
        public string Eposta { get; set; }
        public string Gsm { get; set; }
    }
}
