//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MstYangin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FotoGaleri
    {
        public int Id { get; set; }
        public string ResimUrl { get; set; }
        public string ResimAciklama { get; set; }
    }
}
