//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MstYangin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iletisim
    {
        public int Id { get; set; }
        public string Konu { get; set; }
        public string Ad { get; set; }
        public string Eposta { get; set; }
        public string Baslik { get; set; }
        public string Mesaj { get; set; }
    }
}
