//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MstYangin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public int Id { get; set; }
        public string UrunAd { get; set; }
        public string Icerik { get; set; }
        public string UrunKod { get; set; }
        public Nullable<int> KategoriId { get; set; }
        public string Resim { get; set; }
        public string Baslik { get; set; }
        public string Aciklama { get; set; }
    
        public virtual Kategori Kategori { get; set; }
    }
}
